version: "3.7"
services:
  roundcube:
    image: roundcube/roundcubemail:latest-fpm
    container_name: roundcube
    restart: unless-stopped
    volumes:
      - ./roundcube/www:/var/www/html
      - ./roundcube/config:/var/roundcube/config
      - ./roundcube/db/sqlite:/var/roundcube/db
    expose:
      - "9000"
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://${IMAP_SERVER} #IMAPS endpoint
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://${SMTP_SERVER}  #SMTP endpoint
      - ROUNDCUBEMAIL_USERNAME_DOMAIN=${DOMAIN}
      - ROUNDCUBE_AUTOCOMPLETE_ADDRESS_BOOK_HOST=${ROUNDCUBE_AUTOCOMPLETE_ADDRESS_BOOK_HOST}
      - ROUNDCUBE_AUTOCOMPLETE_ADDRESS_BOOK_BASE_DN=${ROUNDCUBE_AUTOCOMPLETE_ADDRESS_BOOK_BASE_DN}
      - ROUNDCUBE_AUTOCOMPLETE_ADDRESS_BOOK_BIND_DN=${ROUNDCUBE_AUTOCOMPLETE_ADDRESS_BOOK_BIND_DN}
      - ROUNDCUBE_AUTOCOMPLETE_ADDRESS_BOOK_BIND_PASS=${ROUNDCUBE_AUTOCOMPLETE_ADDRESS_BOOK_BIND_PASS}
  roundcubenginx:
    image: nginx:latest
    container_name: roundcubenginx
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - roundcube
    links:
      - roundcube
    volumes:
      - ./roundcube/www:/var/www/html
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/conf.d:/etc/nginx/conf.d
    environment:
      - VIRTUAL_HOST=${VHOST_FQDN}
      - LETSENCRYPT_HOST=${VHOST_FQDN}
      - LETSENCRYPT_EMAIL=${MAIL_ADMIN_USERNAME}@${DOMAIN}
      - NGINX_PHP_CGI=roundcube:9000  # same as roundcubemail container name
